# Generated by Django 3.0.5 on 2020-10-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-publisher__post_date', 'publisher__order_for_simul', 'order']},
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-publisher', 'order'], name='newer_post'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-num_of_downloads', '-recommend_score'], name='dl'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-score', '-recommend_score'], name='popularity'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-num_of_views', '-recommend_score'], name='view'),
        ),
    ]
