# Generated by Django 3.0.5 on 2020-10-22 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20201016_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnail',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='Progress',
        ),
        migrations.DeleteModel(
            name='Thumbnail',
        ),
    ]
