# Generated by Django 3.0.5 on 2021-04-21 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image', '0003_auto_20201023_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-publisher__post_date', 'publisher__order_for_simul', 'order'], 'verbose_name': 'ブログ画像', 'verbose_name_plural': 'ブログ画像'},
        ),
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.IntegerField(default=0, verbose_name='height(px)'),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.IntegerField(default=0, verbose_name='width(px)'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='追加日')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Image', verbose_name='画像')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
            options={
                'verbose_name': 'お気に入り画像',
                'verbose_name_plural': 'お気に入り画像',
                'db_table': 'favorite',
                'ordering': ['-created_at'],
                'unique_together': {('image', 'user')},
            },
        ),
    ]
