# Generated by Django 3.0.5 on 2021-04-22 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProPlanSurvey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('q1', models.CharField(choices=[('buy', '絶対買う'), ('mightBuy', '買うかもしれない'), ('dontBuy', '絶対買わない'), ('noInput', '未回答')], default='noInput', max_length=100, verbose_name='1. もし300円/月のpro planがあったら？')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='回答日')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='回答者')),
            ],
            options={
                'verbose_name': 'pro planアンケート',
                'verbose_name_plural': 'pro planアンケート',
                'ordering': ('-created_at',),
            },
        ),
    ]
