# Generated by Django 3.0 on 2020-01-08 12:38

from django.db import migrations, models
import django.db.models.deletion
import download.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0008_auto_20200107_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0, null=True, verbose_name='進捗')),
                ('ready', models.BooleanField(default=False)),
                ('target', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='search.Blog', verbose_name='対象ブログ')),
            ],
            options={
                'db_table': 'progress',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='順番')),
                ('picture', models.ImageField(upload_to=download.models.get_upload_to, verbose_name='イメージ')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Blog', verbose_name='掲載ブログ')),
            ],
            options={
                'db_table': 'image',
                'unique_together': {('publisher', 'order')},
            },
        ),
    ]
