# Generated by Django 3.0 on 2019-12-15 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0005_auto_20191212_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(max_length=100, verbose_name='順番')),
                ('picture', models.ImageField(upload_to='images/', verbose_name='イメージ')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Blog', verbose_name='掲載ブログ')),
            ],
            options={
                'db_table': 'image',
            },
        ),
    ]
