# Generated by Django 3.0 on 2019-12-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='ready',
        ),
    ]
