# Generated by Django 3.0 on 2019-12-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.IntegerField(verbose_name='順番'),
        ),
    ]
