# Generated by Django 3.0 on 2020-02-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='target',
        ),
        migrations.AddField(
            model_name='progress',
            name='target_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='対象ブログID'),
        ),
    ]
