# Generated by Django 3.0 on 2019-12-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_remove_progress_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
