# Generated by Django 3.0 on 2019-12-15 15:18

from django.db import migrations, models
import download.models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20191216_0018'),
        ('download', '0002_auto_20191215_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(upload_to=download.models.get_upload_to, verbose_name='イメージ'),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('publisher', 'order')},
        ),
    ]
