# Generated by Django 3.0 on 2020-02-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('download', '0002_auto_20200205_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='publisher_id',
            field=models.IntegerField(null=True, verbose_name='掲載ブログID'),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('publisher_id', 'order')},
        ),
        migrations.RemoveField(
            model_name='image',
            name='publisher',
        ),
    ]
