# Generated by Django 3.0.5 on 2021-04-22 21:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='ユーザネーム')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='名前')),
                ('profile_image_uri', models.URLField(blank=True, verbose_name='プロフィール画像(200*200)')),
                ('profile_image_thumbnail_uri', models.URLField(blank=True, verbose_name='プロフィール画像(48*48)')),
                ('profile_image_large_uri', models.URLField(blank=True, verbose_name='プロフィール画像(400*400)')),
                ('max_favorite_images_num', models.IntegerField(default=50, verbose_name='お気に入り画像Max')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日')),
                ('fav_groups', models.ManyToManyField(blank=True, to='main.Group', verbose_name='推しグループ')),
                ('fav_member_hinata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accout_fav_hinata', to='main.Member', verbose_name='日向46推しメン')),
                ('fav_member_sakura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accout_fav_sakura', to='main.Member', verbose_name='櫻坂46推しメン')),
            ],
            options={
                'verbose_name': 'アカウント',
                'verbose_name_plural': 'アカウント',
                'db_table': 'account',
                'ordering': ['-date_joined'],
            },
        ),
    ]
