# Generated by Django 3.0.5 on 2020-10-15 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['post_date', 'order_for_simul']},
        ),
        migrations.RemoveField(
            model_name='group',
            name='netloc',
        ),
        migrations.AddField(
            model_name='group',
            name='blog_url_format',
            field=models.CharField(blank=True, max_length=200, verbose_name='公式ブログ詳細ページURIフォーマット(blog_ctを表す{}を一つ含む)'),
        ),
        migrations.AddField(
            model_name='group',
            name='domain',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='ドメイン'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='key',
            field=models.CharField(blank=True, max_length=30, verbose_name='キー'),
        ),
        migrations.AddField(
            model_name='group',
            name='member_url_format',
            field=models.CharField(blank=True, max_length=200, verbose_name='メンバー詳細ページURIフォーマット(member_ctを表す{}を一つ含む)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=30, verbose_name='グループ名'),
        ),
    ]
