# Generated by Django 3.0.5 on 2020-10-22 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201016_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='publishing_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.Group', verbose_name='掲載グループ'),
        ),
        migrations.AddField(
            model_name='group',
            name='blog_list_paginate_by',
            field=models.IntegerField(default=20, verbose_name='公式ブログリストの1ページ当たりのブログ件数'),
        ),
        migrations.AddField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='活動状況'),
        ),
    ]
