# Generated by Django 3.0.5 on 2021-04-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201023_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['post_date', 'order_for_simul'], 'verbose_name': 'ブログ', 'verbose_name_plural': 'ブログ'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['group_id'], 'verbose_name': 'グループ', 'verbose_name_plural': 'グループ'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['belonging_group', 'generation', 'full_kana'], 'verbose_name': 'メンバー', 'verbose_name_plural': 'メンバー'},
        ),
        migrations.AddField(
            model_name='group',
            name='blog_list_paginate_by_mobile',
            field=models.IntegerField(default=20, verbose_name='(Mobile)公式ブログの1ページ当たりのブログ件数'),
        ),
        migrations.AddField(
            model_name='group',
            name='latest_list_paginate_by',
            field=models.IntegerField(default=12, verbose_name='(PC)公式最新ブログリストのブログ件数'),
        ),
        migrations.AddField(
            model_name='group',
            name='latest_list_paginate_by_mobile',
            field=models.IntegerField(default=12, verbose_name='(Mobile)公式最新ブログリストのブログ件数'),
        ),
        migrations.AlterField(
            model_name='group',
            name='blog_list_paginate_by',
            field=models.IntegerField(default=20, verbose_name='(PC)公式ブログの1ページ当たりのブログ件数'),
        ),
    ]
