# Generated by Django 3.0 on 2020-02-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='order_for_simul',
            field=models.IntegerField(default=0, verbose_name='順番(同時投稿用)'),
        ),
    ]
