# Generated by Django 3.0 on 2019-12-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20191212_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='ct',
            field=models.CharField(max_length=10, verbose_name='ct'),
        ),
    ]
