# Generated by Django 3.0 on 2019-12-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20191212_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_ct',
            field=models.IntegerField(verbose_name='ブログID'),
        ),
        migrations.AlterUniqueTogether(
            name='blog',
            unique_together={('blog_ct', 'writer')},
        ),
    ]
