# Generated by Django 3.0 on 2019-12-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20191216_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='full_eng',
            field=models.CharField(max_length=50, null=True, verbose_name='氏名_英'),
        ),
    ]
