# Generated by Django 3.0 on 2020-01-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_member_full_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='first_eng',
            field=models.CharField(default='', max_length=30, verbose_name='名_英'),
        ),
        migrations.AddField(
            model_name='member',
            name='last_eng',
            field=models.CharField(default='', max_length=30, verbose_name='姓_英'),
        ),
        migrations.AlterField(
            model_name='member',
            name='full_eng',
            field=models.CharField(default='', max_length=50, verbose_name='氏名_英'),
        ),
    ]
